### ISSUE TITLE
[docs] parameters var-name usage

### ISSUE THREAD

**Issue by sbeckeriv** [ruby/rbs#371]
Dearest Maintainer,

I fixed a typo in the syntax file and asked a question (https://github.com/ruby/rbs/pull/369). I dont think I full understand the answer. 

The example given was
```
def foo: (String name, email: String address) -> void
```

I am wondering what the ruby code looks like for this signature. Would it look like this? 
```
def foo(name, email: )
  # somecode
end

foo("sbecker", email: "github@domain")
```

The syntax file https://github.com/ruby/rbs/blame/master/docs/syntax.md#L215 says "parameter with var name". What is the use of the var name? Is it checked against the implementation? If I change foo's implementation variable name is the signature valid? Does a change in variable name need to propagate to the rbs file if the type does not change?  Is it a hint to the user via an error message?  

1 concern is I dont know what it means to me. I can see it being confusing and writing `foo(name: "sbeckeriv", email: github@domain")` because it looks like a keyword param. 

2 concern is code drift. This will happen no matter what with changes to param types or keywords. I can see the lazy version of me not updating name in the rbs file or forgetting to do it. this means another linter is in my future. 

3 concern is correctness. Are these two signatures the same? What if any are the differences. 
```
def foo: (String name, email: String address) -> void
```

```
def foo: (String, email: String address) -> void
```

Once again, thank you for your work and time reviewing my questions.

Dictated but not reviewed,
Becker

**Comment by soutaro** [comment]
Thanks for pointing out this and starting the discussion.

> 1 concern is I dont know what it means to me.

It doesn't mean anything for keyword arguments. The parameter names for positional arguments make some sense I think. It can be used for documentation. We often want to refer to the arguments in the documentation.

Your concern makes sense because keyword arguments can be referred safely by their keyword names.

> 2 concern is code drift.

There is no one-to-one correspondence between the parameter names in method definitions and the names in RBS. We can give more precise/better definitions in RBS, like the following example.

```rb
# def foo: (foo: String, bar: Integer) -> void
#        | (baz: String) -> String
#        | (**String others) -> untyped
def foo(**opts)
end
```

> 3 concern is correctness.

They are the same.

---

I'm thinking of just removing var names from keyword arguments. I don't think it causes serious problems, but agree that we haven't found good usage yet.

**Comment by sbeckeriv** [comment]
Hello @soutaro,

Thank you for your response. I think the biggest question I had was why and that was answer. The main reason is for documentation. The name of the variable can be documented but it has no impact on the code or signature. This would help in a a code hinting system where the comments would not need to be parsed.  Your example of `def foo` is a very informative as well.

Should I leave this issue open to track removing keyword argument var names?

Thank you once again for your time,
Dictated but not reviewed,
Becker
