### ISSUE TITLE
Reader/Writer/Rewindable interfaces

### ISSUE THREAD

**Issue by HoneyryderChuck** [ruby/rbs#425]
There are a couple of agreed-upon interfaces in stream scenarios, which have been supported by ruby since always, and might break with the recent typing.

For instance, `IO.select` works with any object that responds to `#.to_io`, not with [IO objects, like the typing info suggests](https://github.com/ruby/rbs/blob/c64d1f5ba5a4fbc95ffb1d72d783ee39b17d60fe/stdlib/builtin/io.rbs#L525). Likewise, `IO.copy_stream` works if the first argument responds to `read(size, buffer)`, and the second responds to `write(data) -> size`, and [not only with IO objects](https://github.com/ruby/rbs/blob/c64d1f5ba5a4fbc95ffb1d72d783ee39b17d60fe/stdlib/builtin/io.rbs#L517). Both usages will break under typing if these typing declarations are to be kept.

On the former, I suspect that usage of `OpenSSL::SSLSocket` in `IO.select` will break if under typing.

Alternatively, I'd like to suggest the introduction of  `_Reader`,  `_Writer`,  `_Rewindable`, and `_ToIO` interfaces, which can be used in these functions, but also in others where the same criteria applies.

I've been using and supporting such APIs for a long time and they are very convenient, and have also [written about it](https://github.com/ruby/rbs/blob/c64d1f5ba5a4fbc95ffb1d72d783ee39b17d60fe/stdlib/builtin/io.rbs#L517).

**Comment by marcandre** [comment]
I agree, it looks like the sig for IO is incomplete. ` _Reader`, `_Writer`, `_Rewindable` should probably be `IO::_Read`, `IO::_Write` and `IO::_Rewind`. `_ToIO` should be global; if it is much used, maybe `io` (like `string` vs `String`) could be used?

**Comment by marcandre** [comment]
PS: there is already a `_Writeable` interface.

**Comment by HoneyryderChuck** [comment]
I would probably not make it rely on the IO names pace, as buffer type structures such as StringIO or Tempfile aren't IOs, however these interfaces can be applied to it.

**Comment by soutaro** [comment]
Thank you for pointing out the bad types of `IO` methods. (Would you mind opening a PR to fix them?)

Technically it's unnecessary to define a set of common interfaces beforehand, while I know it would be useful. Because the relationship between interfaces and classes/modules are detected implicitly, without any declaration, having API specific and possibly duplicated interfaces works fine.

So, the steps I assume are:

1. Define local interfaces for `IO` methods.
2. Use the interface in `IO` method definitions.
3. Promote it if we find they are useful for other methods too.
