### ISSUE TITLE
Ability to point collection to local definitions

### ISSUE THREAD

**Issue by wagenet** [ruby/rbs#842]
I'd like to be able to have an `rbs_collection.yaml` where the source is a local path.

In my case, there is no definition for the stripe gem in gem_rbs_collection. So I generated one with typeprof. It's not really properly validated so I don't yet want to send a PR to gem_rbs_collection, but I'd like to try to use it. I'm also using steep and typeprof's collection support.

**Comment by pocke** [comment]
Thanks for reporting the issue! Your feature request is pretty reasonable. I'm planning to implement the same feature since a few days ago because I have a similar problem with testing gem_rbs_collection itself and the feature will solve it.


I'll design and implement the feature soon, but perhaps I will not make it in time for Ruby 3.1 release, so please wait for a while :pray:
